# Generated by Django 3.2.8 on 2021-11-04 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this object was first created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when this object was last updated.', null=True)),
                ('question', models.TextField(help_text='The question')),
                ('answer', models.TextField(help_text='The answer to the question')),
                ('position', models.PositiveSmallIntegerField(help_text='The position in which the question should be displayed within its category section - 1 = 1st')),
            ],
            options={
                'verbose_name_plural': 'FAQ Questions',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this object was first created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when this object was last updated.', null=True)),
                ('name', models.CharField(help_text='The title of the category.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this object was first created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when this object was last updated.', null=True)),
                ('name', models.CharField(help_text='Name of the person sending the message', max_length=100)),
                ('email', models.EmailField(help_text='The email address that I should reply to', max_length=254)),
                ('subject', models.TextField(help_text='The subject of the message')),
                ('message', models.TextField(help_text='Please describe the issue in as much detail as possible')),
                ('read', models.BooleanField(default=False, help_text='whether or not the message has been read')),
                ('related_user_account', models.ForeignKey(blank=True, help_text='The user account, if the user was logged in', null=True, on_delete=models.SET(users.utils.get_sentinel_user), related_name='support_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Support Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='faqcategory',
            index=models.Index(fields=['name'], name='support_faq_name_f6a7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='faqcategory',
            index=models.Index(fields=['created_at'], name='support_faq_created_c55873_idx'),
        ),
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(help_text='The category of the FAQ Question', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='support.faqcategory'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['name'], name='support_sup_name_ab0dee_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['created_at'], name='support_sup_created_407332_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['question'], name='support_faq_questio_e09b5c_idx'),
        ),
    ]
