# Generated by Django 3.2.9 on 2021-11-21 12:25

import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportmessage",
            name="related_user_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The user account, if the user was logged in",
                null=True,
                on_delete=models.SET(users.utils.get_sentinel_user),
                related_name="support_messages_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="faqcategory",
            index=models.Index(fields=["name"], name="support_faq_name_f6a7ec_idx"),
        ),
        migrations.AddIndex(
            model_name="faqcategory",
            index=models.Index(
                fields=["created_at"], name="support_faq_created_c55873_idx"
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                help_text="The category of the FAQ Question",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="support.faqcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(fields=["name"], name="support_sup_name_ab0dee_idx"),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(
                fields=["created_at"], name="support_sup_created_407332_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="faq",
            index=models.Index(
                fields=["question"], name="support_faq_questio_e09b5c_idx"
            ),
        ),
    ]
