version: '3'

services:
  # Database container for PostgreSQL
  db:
    env_file:
      - .env.dev
    image: postgres:13.4
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data:delegated

  # Reverse proxy container for Nginx
  nginx:
    image: nginx:1.21.0
    ports:
      - "8000:80"
    volumes:
      - ./collabl/config/nginx/conf.d:/etc/nginx/conf.d
      - ./collabl/static/compiled/:/compiled:delegated
      - ./collabl/static/admin/:/admin:delegated
    depends_on:
      - web

  # Backend container, with both Django + Gunicorn
  web:
    env_file:
      - .env.dev
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/collabl/src:delegated
      - static:/opt/services/collabl/static:delegated
      - media:/opt/services/collabl/media:delegated
      - logs:/opt/services/collabl/logs:delegated
    depends_on:
      - db
      - redis
    links:
      - db:db

  # Message queue for Celery tasks
  redis:
    image: redis:6.2.2-alpine

  # Container specifically for Celery workers
  worker:
    env_file:
      - .env.dev
    working_dir: /opt/services/collabl/src/collabl
    build: .
    # In prod, we may want to pass the --uid of the user to silence warnings
    command: celery -A collabl worker -l info
    # command: sh -c "celery -A collabl worker --beat --loglevel=INFO"
    volumes:
      - .:/opt/services/collabl/src:delegated
      - static:/opt/services/collabl/static:delegated
      - media:/opt/services/collabl/media:delegated
    depends_on:
      - db
      - redis

# Persist certain volumes
volumes:
  logs:
  db_volume:
  static:
  media:
