version: '3.8'

services:
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000 # new
    volumes:
      - .:/opt/services/collabl/src:delegated
      - static:/opt/services/collabl/static:delegated
      - media:/opt/services/collabl/media:delegated
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  # Reverse proxy container for Nginx
  nginx:
    restart: unless-stopped
    image: nginx:1.21.0
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./collabl/config/nginx/prod-conf.d:/etc/nginx/conf.d
      - ./collabl/static/compiled/:/compiled:delegated
      - ./collabl/static/admin/:/admin:delegated
    depends_on:
      - web

  # Message queue for Celery tasks
  redis:
    image: redis:6.2.4-alpine

  # Container specifically for Celery workers
  worker:
    working_dir: /opt/services/collabl/src/collabl
    build: .
    # In prod, we may want to pass the --uid of the user to silence warnings
    command: celery -A collabl worker -l info
#    command: sh -c "celery -A collabl worker -l info && celery -A collabl worker --beat --loglevel=INFO" # Start both a worker and beat, for the nightly deletion task.
    volumes:
      - .:/opt/services/collabl/src:delegated
      - static:/opt/services/collabl/static:delegated
      - media:/opt/services/collabl/media:delegated
      - logs:/opt/services/collabl/logs:delegated
    depends_on:
      - redis

# Persist certain volumes
volumes:
  logs:
  static:
  media:
