# Generated by Django 3.2.9 on 2021-11-06 23:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchatmessage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='groupjoinrequest',
            options={'verbose_name_plural': 'Join Requests'},
        ),
        migrations.AlterModelOptions(
            name='groupprofileimage',
            options={'verbose_name_plural': 'Profile Images'},
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of the Group', related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='Users who receive email updates from the Group', related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
