# Generated by Django 3.2.9 on 2021-11-22 18:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ("created_at",), "verbose_name_plural": "Groups"},
        ),
        migrations.AlterModelOptions(
            name="groupjoinrequest",
            options={
                "ordering": ("created_at",),
                "verbose_name_plural": "Join Requests",
            },
        ),
        migrations.AlterUniqueTogether(
            name="groupjoinrequest",
            unique_together={("user", "group", "status")},
        ),
    ]
