# Generated by Django 3.2.9 on 2021-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20211106_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(default='exmaple description', help_text="A description of the group and it's causes", max_length=500),
            preserve_default=False,
        ),
    ]
