# Generated by Django 3.2.9 on 2021-11-07 15:20

from django.conf import settings
from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text='Users with Administrative Rights', related_name='admin_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the group', on_delete=models.SET(users.utils.get_sentinel_user), related_name='groups_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
