# Generated by Django 3.2.9 on 2021-11-07 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_auto_20211107_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchatmessage',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group where the message was written', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='groupchatmessage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who wrote the message', on_delete=models.SET(users.utils.get_sentinel_user), related_name='group_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
