# Generated by Django 3.2.9 on 2021-11-07 16:49

from django.conf import settings
from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0005_auto_20211107_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupjoinrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, help_text='User who handled the request', null=True, on_delete=models.SET(users.utils.get_sentinel_user), related_name='group_join_requests_handled', to=settings.AUTH_USER_MODEL),
        ),
    ]
