# Generated by Django 3.2.9 on 2021-11-08 16:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_alter_groupjoinrequest_handled_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupjoinrequest',
            unique_together={('user', 'group')},
        ),
    ]
