# Generated by Django 3.2.9 on 2021-11-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_groupjoinrequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='profile_image',
        ),
        migrations.DeleteModel(
            name='GroupChatMessage',
        ),
        migrations.DeleteModel(
            name='GroupProfileImage',
        ),
    ]
