# Generated by Django 3.2.9 on 2021-11-21 12:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when this object was first created.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of when this object was last updated.",
                        null=True,
                    ),
                ),
                ("question", models.TextField(help_text="The question")),
                ("answer", models.TextField(help_text="The answer to the question")),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="The position in which the question should be displayed within its category section - 1 = 1st"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FAQ Questions",
                "ordering": ["question"],
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when this object was first created.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of when this object was last updated.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The title of the category.", max_length=50
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "FAQ Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when this object was first created.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of when this object was last updated.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the person sending the message",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="The email address that I should reply to",
                        max_length=254,
                    ),
                ),
                ("subject", models.TextField(help_text="The subject of the message")),
                (
                    "message",
                    models.TextField(
                        help_text="Please describe the issue in as much detail as possible"
                    ),
                ),
                (
                    "read",
                    models.BooleanField(
                        default=False,
                        help_text="whether or not the message has been read",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Support Messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
