# Generated by Django 3.2.9 on 2021-11-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='subject',
        ),
    ]
