# Generated by Django 3.2.9 on 2021-11-14 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborations', '0008_delete_collaborationchatmessage'),
        ('groups', '0008_auto_20211114_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this object was first created.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when this object was last updated.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp of when (if) this object was soft deleted.', null=True)),
                ('message', models.TextField(help_text='The message itself')),
                ('collaboration', models.ForeignKey(blank=True, help_text='The Collaboration this message belongs to - blank if it is a general group message', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='collaborations.collaboration')),
                ('group', models.ForeignKey(blank=True, help_text='The group where the message was written', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='groups.group')),
                ('user', models.ForeignKey(help_text='User who wrote the message', on_delete=models.SET(users.utils.get_sentinel_user), related_name='collaboration_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_chatme_created_888e17_idx'),
        ),
    ]
