# Generated by Django 3.2.9 on 2021-11-14 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20211114_1351'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborations', '0008_delete_collaborationchatmessage'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_chatme_created_888e17_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='chat_messag_created_b6b51c_idx'),
        ),
    ]
