# Generated by Django 3.2.9 on 2021-11-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("collaborations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="collaboration",
            field=models.ForeignKey(
                blank=True,
                help_text="The Collaboration this message belongs to - blank if it is a general group message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="collaborations.collaboration",
            ),
        ),
    ]
