# Generated by Django 3.2.9 on 2021-11-21 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('chat', '0002_message_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The group where the message was written', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='groups.group'),
        ),
    ]
