"""REQUEST STATUS"""

REQUEST_STATUS_PENDING: str = "Pending"
REQUEST_STATUS_APPROVED: str = "Approved"
REQUEST_STATUS_DENIED: str = "Denied"

REQUEST_STATUS_CHOICES: tuple = (
    (REQUEST_STATUS_PENDING, "Pending"),
    (REQUEST_STATUS_APPROVED, "Approved"),
    (REQUEST_STATUS_DENIED, "Denied"),
)