from groups.constants import MEMBERSHIP_STATUS_PENDING, MEMBERSHIP_STATUS_CURRENT, MEMBERSHIP_STATUS_IGNORED, \
    MEMBERSHIP_STATUS_REMOVED, MEMBERSHIP_STATUS_LEFT, MEMBERSHIP_ACTION_APPROVE, MEMBERSHIP_ACTION_IGNORE, \
    MEMBERSHIP_ACTION_REMOVE, MEMBERSHIP_ACTION_MAKE_ADMIN, MEMBERSHIP_ACTION_CLEAR_SELECTION


def group_views_context(request):
    return {
        'MEMBERSHIP_STATUS_PENDING': MEMBERSHIP_STATUS_PENDING,
        'MEMBERSHIP_STATUS_CURRENT': MEMBERSHIP_STATUS_CURRENT,
        'MEMBERSHIP_STATUS_IGNORED': MEMBERSHIP_STATUS_IGNORED,
        'MEMBERSHIP_STATUS_REMOVED': MEMBERSHIP_STATUS_REMOVED,
        'MEMBERSHIP_STATUS_LEFT': MEMBERSHIP_STATUS_LEFT,
        'MEMBERSHIP_ACTION_APPROVE': MEMBERSHIP_ACTION_APPROVE,
        'MEMBERSHIP_ACTION_IGNORE': MEMBERSHIP_ACTION_IGNORE,
        'MEMBERSHIP_ACTION_REMOVE': MEMBERSHIP_ACTION_REMOVE,
        'MEMBERSHIP_ACTION_MAKE_ADMIN': MEMBERSHIP_ACTION_MAKE_ADMIN,
        'MEMBERSHIP_ACTION_CLEAR_SELECTION': MEMBERSHIP_ACTION_CLEAR_SELECTION,
    }
