from collaborations.constants import (
    COLLABORATION_STATUS_PLANNING,
    COLLABORATION_STATUS_ONGOING,
    COLLABORATION_STATUS_COMPLETED,
    COLLABORATION_STATUS_ALL,
    COMPLETE_TASK,
    UNDO_COMPLETE_TASK,
)
from groups.constants import (
    MEMBERSHIP_STATUS_PENDING,
    MEMBERSHIP_STATUS_CURRENT,
    MEMBERSHIP_STATUS_IGNORED,
    MEMBERSHIP_ACTION_APPROVE,
    MEMBERSHIP_ACTION_IGNORE,
    MEMBERSHIP_ACTION_REMOVE,
    MEMBERSHIP_ACTION_MAKE_ADMIN,
    MEMBERSHIP_ACTION_CLEAR_SELECTION,
    ANNOUNCEMENTS_FILTER_LATEST,
    ANNOUNCEMENTS_FILTER_ALL,
    MEMBERSHIP_STATUS_ADMIN,
)


def group_views_context(request):
    """
    This context is used to populate various dropdown menus on the group detail page, ensuring equality of values and
    allowing simpler view logic, with regards to filtering.
    """
    return {
        "MEMBERSHIP_STATUS_PENDING": MEMBERSHIP_STATUS_PENDING,
        "MEMBERSHIP_STATUS_CURRENT": MEMBERSHIP_STATUS_CURRENT,
        "MEMBERSHIP_STATUS_IGNORED": MEMBERSHIP_STATUS_IGNORED,
        "MEMBERSHIP_STATUS_ADMIN": MEMBERSHIP_STATUS_ADMIN,
        "MEMBERSHIP_ACTION_APPROVE": MEMBERSHIP_ACTION_APPROVE,
        "MEMBERSHIP_ACTION_IGNORE": MEMBERSHIP_ACTION_IGNORE,
        "MEMBERSHIP_ACTION_REMOVE": MEMBERSHIP_ACTION_REMOVE,
        "MEMBERSHIP_ACTION_MAKE_ADMIN": MEMBERSHIP_ACTION_MAKE_ADMIN,
        "MEMBERSHIP_ACTION_CLEAR_SELECTION": MEMBERSHIP_ACTION_CLEAR_SELECTION,
        "ANNOUNCEMENTS_FILTER_LATEST": ANNOUNCEMENTS_FILTER_LATEST,
        "ANNOUNCEMENTS_FILTER_ALL": ANNOUNCEMENTS_FILTER_ALL,
        "COLLABORATION_STATUS_ALL": COLLABORATION_STATUS_ALL,
        "COLLABORATION_STATUS_PLANNING": COLLABORATION_STATUS_PLANNING,
        "COLLABORATION_STATUS_ONGOING": COLLABORATION_STATUS_ONGOING,
        "COLLABORATION_STATUS_COMPLETED": COLLABORATION_STATUS_COMPLETED,
        "COMPLETE_TASK": COMPLETE_TASK,
        "UNDO_COMPLETE_TASK": UNDO_COMPLETE_TASK,
    }
