# Generated by Django 3.2.9 on 2021-11-21 12:25

import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collaborations", "0001_initial"),
        ("groups", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborationtask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User who should complete the task",
                null=True,
                on_delete=models.SET(users.utils.get_sentinel_user),
                related_name="tasks_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborationtask",
            name="collaboration",
            field=models.ForeignKey(
                help_text="The Collaboration this element belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="collaborations.collaboration",
            ),
        ),
        migrations.AddField(
            model_name="collaborationtask",
            name="completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who completed the task/reached the milestone",
                null=True,
                on_delete=models.SET(users.utils.get_sentinel_user),
                related_name="tasks_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborationtask",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks that must be completed before this task",
                related_name="dependant_tasks",
                to="collaborations.CollaborationTask",
            ),
        ),
        migrations.AddField(
            model_name="collaborationtask",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags showing certain properties that relate to multiple tasks e.g. 'Admin Task'",
                related_name="tasks",
                to="collaborations.CollaborationTaskTag",
            ),
        ),
        migrations.AddField(
            model_name="collaborationmilestone",
            name="collaboration",
            field=models.ForeignKey(
                help_text="The Collaboration this element belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="collaborations.collaboration",
            ),
        ),
        migrations.AddField(
            model_name="collaborationmilestone",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tasks that must be completed to each this milestones",
                related_name="milestone",
                to="collaborations.CollaborationTask",
            ),
        ),
        migrations.AddField(
            model_name="collaborationfile",
            name="collaboration",
            field=models.ForeignKey(
                help_text="The Collaboration this file belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="collaborations.collaboration",
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the collaboration",
                on_delete=models.SET(users.utils.get_sentinel_user),
                related_name="collaborations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaboration",
            name="related_group",
            field=models.ForeignKey(
                help_text="The Group this collaboration belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborations",
                to="groups.group",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationtask",
            index=models.Index(
                fields=["collaboration", "position"],
                name="collaborati_collabo_6348b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationtask",
            index=models.Index(
                fields=["collaboration", "-position"],
                name="collaborati_collabo_39435f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationtask",
            index=models.Index(
                fields=["collaboration"], name="collaborati_collabo_63ef8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationtask",
            index=models.Index(
                fields=["position"], name="collaborati_positio_ad292f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationtask",
            index=models.Index(
                fields=["-position"], name="collaborati_positio_d621f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationmilestone",
            index=models.Index(
                fields=["collaboration", "position"],
                name="collaborati_collabo_bc0269_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationmilestone",
            index=models.Index(
                fields=["collaboration", "-position"],
                name="collaborati_collabo_fb50ea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationmilestone",
            index=models.Index(
                fields=["collaboration"], name="collaborati_collabo_9efee9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationmilestone",
            index=models.Index(
                fields=["position"], name="collaborati_positio_0f0da1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationmilestone",
            index=models.Index(
                fields=["-position"], name="collaborati_positio_f3a031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationfile",
            index=models.Index(
                fields=["created_at"], name="collaborati_created_3e759b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationfile",
            index=models.Index(
                fields=["collaboration"], name="collaborati_collabo_4497df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaborationfile",
            index=models.Index(fields=["name"], name="collaborati_name_4d1cd3_idx"),
        ),
        migrations.AddIndex(
            model_name="collaboration",
            index=models.Index(
                fields=["created_at"], name="collaborati_created_33e1c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collaboration",
            index=models.Index(fields=["name"], name="collaborati_name_ad6d7d_idx"),
        ),
        migrations.AddIndex(
            model_name="collaboration",
            index=models.Index(fields=["slug"], name="collaborati_slug_174615_idx"),
        ),
    ]
