# Generated by Django 3.2.9 on 2021-11-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborations", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborationmilestone",
            name="position",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="The position of the element (1 = 1st)"
            ),
        ),
        migrations.AlterField(
            model_name="collaborationtask",
            name="position",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="The position of the element (1 = 1st)"
            ),
        ),
    ]
