# Generated by Django 3.2.9 on 2022-01-07 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collaborations", "0003_auto_20211123_1840"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collaboration",
            options={"ordering": ["name"], "verbose_name_plural": "Collaborations"},
        ),
    ]
