# Generated by Django 3.2.9 on 2022-01-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborations", "0006_collaborationtask_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborationtask",
            name="prompt_for_details_on_completion",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user who completes the task should be prompted to enter further details",
            ),
        ),
    ]
