# Generated by Django 3.2.9 on 2021-11-06 23:00

from django.conf import settings
from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaboration',
            options={'verbose_name_plural': 'Collaborations'},
        ),
        migrations.AlterModelOptions(
            name='collaborationchatmessage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='collaborationfile',
            options={'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='collaborationtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User who should complete the task', null=True, on_delete=models.SET(users.utils.get_sentinel_user), related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborationtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who completed the task', null=True, on_delete=models.SET(users.utils.get_sentinel_user), related_name='tasks_completed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborationtask',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Files that are connected to a task', related_name='tasks', to='collaborations.CollaborationFile'),
        ),
        migrations.AlterField(
            model_name='collaborationtask',
            name='prerequisite_tasks',
            field=models.ManyToManyField(blank=True, help_text='Tasks that must be completed before this task', related_name='dependant_tasks', to='collaborations.CollaborationTask'),
        ),
        migrations.AlterField(
            model_name='collaborationtask',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text="Tags showing certain properties that relate to multiple tasks e.g. 'Admin Task'", related_name='tasks', to='collaborations.CollaborationTaskTag'),
        ),
    ]
