# Generated by Django 3.2.9 on 2022-01-08 19:33

from django.db import migrations, models
import dynamo.storages


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0004_alter_collaboration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='image',
            field=models.FileField(blank=True, help_text='Image for the collaboration. Please aim to keep this below 1mb in size.', null=True, upload_to=dynamo.storages.collaboration_based_upload_to),
        ),
    ]
