# Generated by Django 3.2.9 on 2021-11-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0004_auto_20211114_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborationelement',
            old_name='task_tags',
            new_name='tags',
        ),
    ]
