# Generated by Django 3.2.9 on 2021-11-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0005_rename_task_tags_collaborationelement_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborationelement',
            old_name='milestone_target',
            new_name='target',
        ),
    ]
