# Generated by Django 3.2.9 on 2021-11-14 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0006_rename_milestone_target_collaborationelement_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborationelement',
            old_name='target',
            new_name='target_date',
        ),
    ]
