# Generated by Django 3.2.9 on 2021-11-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0007_rename_target_collaborationelement_target_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollaborationChatMessage',
        ),
    ]
