# Generated by Django 3.2.9 on 2021-11-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0008_delete_collaborationchatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationelement',
            name='description',
            field=models.TextField(blank=True, help_text='A further description of the task and what is required', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='collaborationelement',
            name='target_date',
            field=models.DateTimeField(blank=True, help_text='A date by which the group should aim to reach this milestone', null=True),
        ),
    ]
