# Generated by Django 3.2.9 on 2021-11-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0009_auto_20211114_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationelement',
            name='reference',
            field=models.CharField(default='REF', help_text='An auto-generated task reference, used to assign task as prerequisates', max_length=255),
        ),
    ]
