# Generated by Django 3.2.9 on 2021-11-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborations', '0010_collaborationelement_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborationelement',
            options={'ordering': ['collaboration', 'position'], 'verbose_name_plural': 'Elements'},
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='status',
        ),
        migrations.AddField(
            model_name='collaborationelement',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Any information relevant to the completion of this task. ', max_length=500, null=True),
        ),
    ]
