# Generated by Django 3.2.9 on 2021-12-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_auto_20211227_2132"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="admins",
        ),
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="group",
            name="subscribers",
        ),
    ]
