# Generated by Django 3.2.9 on 2021-12-27 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0005_auto_20211227_2137"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when this object was first created.",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of when this object was last updated.",
                        null=True,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when (if) this object was soft deleted.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pending", "Pending"),
                            ("Current", "Current"),
                            ("Denied", "Denied"),
                            ("Removed", "Removed"),
                        ],
                        default="Pending",
                        help_text="The status of the membership",
                        max_length=100,
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        default=False, help_text="Whether the user has admin rights"
                    ),
                ),
                (
                    "is_subscribed",
                    models.BooleanField(
                        default=True, help_text="Whether the user gets email updates"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="groups.group",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who handled the request",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.SET(users.utils.get_sentinel_user),
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Memberships",
                "ordering": ("-created_at", "-updated_at"),
                "unique_together": {("user", "group")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who are members of the Group",
                through="groups.Membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
