# Generated by Django 3.2.9 on 2021-12-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0006_auto_20211227_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="is_subscribed",
            field=models.BooleanField(
                default=False, help_text="Whether the user gets email updates"
            ),
        ),
    ]
