name: Main
on: [push, pull_request]
jobs:

  test:
    name: "Test Code"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:

      - uses: actions/checkout@v2

      - name: Set Up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Print Python Version
        run: |
          python3 --version

      - name: Generate .env File
        run: |
          touch .env.dev
          echo POSTGRES_DB_PORT=5432 >> .env.dev
          echo POSTGRES_DB_HOST=db >> .env.dev
          echo POSTGRES_USER=pg_user >> .env.dev
          echo POSTGRES_DB=postgres_db >> .env.dev
          echo DJANGO_ALLOWED_HOSTS='localhost 127.0.0.1' >> .env.dev
          echo DJANGO_DEBUG_STATUS=True >> .env.dev
          echo SITE_PROTOCOL=http:// >> .env.dev
          echo SITE_DOMAIN='127.0.0.1:8000' >> .env.dev
          RANDOMKEY=$(python3 -c 'import secrets; print(secrets.token_hex(100))')
          echo DJANGO_SECRET_KEY="${RANDOMKEY}" >> .env.dev

      - name: Print .env File
        run: cat .env.dev

      - name: Build Docker Containers
        run: make -f make-dev build

      - name: Make Database Migrations
        run: make -f make-dev up

      - name: Make Database Migrations
        run: make -f make-dev migrate

      - name: Run Tests
        run: make -f make-dev run_django_tests
  

  deploy:
    name: "Deploy to Server & Rebuild Docker Containers"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          SSH_USER_SUDO_PASS: ${{ secrets.SSH_USER_SUDO_PASS }}

      - name: Pull Down the New Files
        run: ssh prod 'cd app && git fetch && git reset --hard origin/main'

      - name: Rebuild Docker Containers
        run: ssh prod 'cd app && sudo make -f make-prod build'

      - name: Migrate Database Changes
        run: ssh prod 'cd app && make -f make-prod migrate'

      - name: Restart Docker Containers
        run: ssh prod 'cd app && make -f make-prod restart'