name: Main
on: [push, pull_request]
jobs:

  test:
    name: "Test Code"
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Print python version
        run: |
          python3 --version

      - name: Generate env file
        run: |
          touch .env.dev
          echo POSTGRES_DB_PORT=1000 >> .env.dev
          echo POSTGRES_DB_HOST=db >> .env.dev
          echo POSTGRES_USER=pg_user >> .env.dev
          echo POSTGRES_DB=postgres_db >> .env.dev
          echo DJANGO_SETTINGS_MODULE=collabl.settings >> .env.dev
          echo DJANGO_ALLOWED_HOSTS='localhost 127.0.0.1' >> .env.dev
          echo DJANGO_DEBUG_STATUS=True >> .env.dev
          echo SITE_PROTOCOL='http://' >> .env.dev
          echo SITE_DOMAIN='127.0.0.1:8000' >> .env.dev
          RANDOMKEY=$(python3 -c 'import secrets; print(secrets.token_hex(100))')
          echo DJANGO_SECRET_KEY="${RANDOMKEY}" >> .env.dev

      - name: Print env file
        run: |
          cat .env.dev

      - name: Build docker containters
        run: |
          make -f make-dev build

      - name: Run Tests
        run: |
          make -f make-dev run_django_tests
  

  deploy:
    name: "Deploy to prod server"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}
          SSH_USER_SUDO_PASS: ${{ secrets.SSH_USER_SUDO_PASS }}

      - name: Check out the new files
        run: ssh prod 'cd app && git fetch && git reset --hard origin/main'

      - name: Migrate database changes
        run: ssh prod 'cd app && make -f make-prod migrate'

      - name: Rebuild docker containers
        run: ssh prod 'cd app && sudo make -f make-prod build'

      - name: Restart docker containers
        run: ssh prod 'cd app && make -f make-prod restart'